### ISSUE TITLE
Start of the code review process 👋

### ISSUE THREAD

**Issue by olivierobert** [automch-code/google-scraping#20]
Hello 👋 , thank you for your effort on the code submission. I am Olivier and I am happy to be the reviewer for our code review session.

During the review process, I would like to know more about your decisions, so I will create issues in some areas where there could be more improvements regarding your submission. Since solving every possible problem would take too long, I will prioritize the most important ones.

At the same time, please keep in mind that this is a bi-directional process, and I would love to hear back from you as well. Therefore, do not hesitate to ask questions or share your opinions about the implementation (if any) during the process.

We expect the code review process to be completed within 2-3 days. As a result, please make sure you are responsive during this process. If you need more time, please let us know as soon as possible so we can plan accordingly.

If we are aligned on any issue, and you would like to correct them, please address the issue using a proper git flow (creating a new branch, opening a Pull Request (PR) per issue, and merging the code when you are ready), and I will follow up on those fixes. Just so you know, you don't have to close any of my created issues after merging your PRs; I will help verify and close them for you once they pass. 😇

In the end, I do hope that you find the process enjoyable. Good luck and happy coding. 🤘

**Comment by olivierobert** [comment]
I have now completed the first round of review and look forward for your feedback on all open issues.

**Comment by automch-code** [comment]
Hello, Mr. Olivier
Thank you for your review kub.
I'm so excited for reviewing and I'll check as soon as possible.
Feel free to ask if you have any question kub

**Comment by olivierobert** [comment]
I have completed the second round of reviews ✅ Please review my comments. It would be great to have some additional feedback. 

Let's aim to finish this code review process by tomorrow 📆

**Comment by olivierobert** [comment]
Thank you for all your efforts @automch-code It is now time to wrap up this stage of the recruitment process. We will provide our feedback to you by email shortly.
