### ISSUE TITLE
[Bug] Frontend application fails to start

### ISSUE THREAD

**Issue by olivierobert** [automch-code/google-scraping#21]
## Issue

Upon cloning the application, I set up the application with `make start` and `make migrate`. 

At first, all services are running:

<img width="1059" alt="image" src="https://github.com/automch-code/google-scraping/assets/696529/805838f2-0898-4ac0-a457-7beaf9c07224">

The frontend application is not reachable:

<img width="1132" alt="image" src="https://github.com/automch-code/google-scraping/assets/696529/df3aa9f4-59fa-4efb-a1ca-1f82ef6d6dcb">

When checking the logs and docker services, the frontend application seems to be stuck on restarting every 60 seconds:

<img width="778" alt="image" src="https://github.com/automch-code/google-scraping/assets/696529/faa0bb6d-989b-4dae-94e6-30206c205b2a">

<img width="1106" alt="image" src="https://github.com/automch-code/google-scraping/assets/696529/0cc930fb-5592-4308-b6d1-5c15f18204fb">

**Comment by automch-code** [comment]
Hello Olivier
I try clone and run the process and figure out on different machines 
Have you tried `make restart` already ?

**Comment by olivierobert** [comment]
Yes. Already done that. Initially I saw an error with `pnpm` but I cannot reproduce it.

**Comment by automch-code** [comment]
Hello Olivier
I'm not sure this problem relates to the docker image architecture
Can you try `uname -m`, I will change my image platform using arm architech if you're using MacBook (like M1, M2,..)
I'll try to investigate if it relates or not.

**Comment by olivierobert** [comment]
Indeed, it could be related to ARM architecture 👍 Let's leave it as-is. It is not a blocker and you provided sufficient feedback.
