### ISSUE TITLE
[Chore] Improve async processing of keywords

### ISSUE THREAD

**Issue by olivierobert** [automch-code/google-scraping#22]
## Issue

Upon uploading keywords, the scraping will be performed asynchronously but all keywords will be processed in a loop.

https://github.com/automch-code/google-scraping/blob/3a18502d9f4a97c31916a0e90857c9d6489412b9/backend/app/jobs/import_keywords_job.rb#L9-L21

> [!WARNING]
> Rescueing a block with `Exception` is dangerous as it acts as a catch-all. It is best to raise custom errors (e.g., GoogleScraper could raise a custom error) and catch more specific errors.

## Expected

- Keywords should be stored in the database with a flag to track the scraping status per keyword.
- A distinct background job to scrap the Google page is then scheduled for each keyword.

The benefits is that thehe scraping of each keyword is isolated, i.e., one could error out while others could be successful.

**Comment by automch-code** [comment]
Hello, Olivier
I have improved my async processing already, I moved the Scrapping logic to the background process after_save so each keyword will scrap in parallel without blocking each other.
I am not sure my implementation is a good practice.
If you have any recommendations or approaches I really happy to hear them from you kub. 😊

**Comment by automch-code** [comment]
[this is pull request imporve async process](https://github.com/automch-code/google-scraping/pull/28)

**Comment by olivierobert** [comment]
Reviewed the changes and added a few comments 📖

**Comment by automch-code** [comment]
hello Olivier
I have checked and finished your review already.
my commit moving validate logic from controller to model [here](https://github.com/automch-code/google-scraping/pull/28/commits/52a39f6d9a49880c6aba91df6db44534e9743fb5)
I already improved the async process [here](https://github.com/automch-code/google-scraping/pull/28/commits/b9b620bdb4680984f54aa24df716678af6366c7a)

**Comment by olivierobert** [comment]
I have reviewed, and the improvements are good. Testing could still be improved, but the overall architecture is much more sound now.
