### ISSUE TITLE
[Chore] Add test for the Google Scraper

### ISSUE THREAD

**Issue by olivierobert** [automch-code/google-scraping#26]
## Issue

Automated tests do not cover the core business logic: scraping.

## Expected

While 100% test coverage is not required for this code challenge, all critical paths of the application should be unit-tested (and, ideally, UI-tested). So the following should be covered:

- CSV parsing 
- Keyword scraping

> ![NOTE]
> Writing tests for an asynchronous process that makes HTTP requests is where the tricky parts lie. This is why you are expected to propose a valid solution.

**Comment by automch-code** [comment]
Hello, Olivier 
thank you for letting me know. I will proceed to add RSpec for core logic.

**Comment by olivierobert** [comment]
As a hint, you will need to record the request to Google. A team such as https://github.com/vcr/vcr is usually the easiest go-to tool.

**Comment by automch-code** [comment]
Hello Olivier
I try to use Webmock when GoogleScraper.call [here](https://github.com/automch-code/google-scraping/pull/29) pull-request.
I'm not sure if I do it the right way.

**Comment by olivierobert** [comment]
The usage of Webmock is sound. The implementation is sufficient to show you can research a new tool and apply it 💪
